### ISSUE TITLE
implement react-router to handle page changes with user context

### ISSUE THREAD

**Issue by sammiefrog** [jtodd0515/journal-app#14]
- [x] create pages to switch between on the front end

- [x] wrap app in user context

- [x] block certain path to users homepage if not logged in
