### ISSUE TITLE
Authentication for user login

### ISSUE THREAD

**Issue by jtodd0515** [jtodd0515/journal-app#4]
Add authenication and create user login. This is a large scoped item and is broken down into multiple stories related to database structure, api routes, and form submission.

### Stories

- [x] Set up a mongoose user model for the database which includes the fields described below in bullet 3
- [x] Install and configure the base passport js local strategy: http://www.passportjs.org/packages/passport-local/
- [x] Create a POST signup route at `/api/signup` which accepts the following:
    - Username: string, unique, optional
    - Email: string, required, unique
    - Password: Required, string
    - Name: first and last, required, strings
    - Verified: boolean, default false (A flag which starts as false and prevents a user from perfoming actions until true; usually done via an emailed link)
- [x] Set up a POST route at `/api/login` which accepts username + password and calls into the passport.authenticate chain
- [x] Create a validation service which provides functions to validate database fields such as email, password etc. These can most commonly be in the form of `<regular expression>.test(<input>);` and return a boolean 
- [x] A form on the frontend which posts data above in order to sign up
- [x] A form on the front end which posts username + password data in order to log in.

**Comment by krab7191** [comment]
This is a rather large item so I'm converting to an epic.

**Comment by krab7191** [comment]
Per discussion in scrum, decide which authentication strategy to move forward with first. I had written this assuming a passport.local strat, so once decided I will rewrite the Epic to reflect and update associated stories.
